Repository netlify/next-on-netlify, pull requests merged in 2020-12, with the labels that each got.

#105 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type: chore

#114 update README to explain the future of next on netlify
  .prettierignore
  README.md
Labels: type: chore

#117 Add finished to res
  lib/templates/createResponseObject.js
Labels: type: bug

#118 Fix cypress:local: Skip test for cache control header
  cypress/integration/optionalCatchAll_at_root_spec.js
Labels: type: bug

#119 Expose event and context of Netlify Function in Next.js pages and API routes
  README.md
  cypress/fixtures/pages/api/context.js
  cypress/fixtures/pages/getServerSideProps/context.js
  cypress/fixtures/pages/getServerSideProps/wait-on-empty-event-loop/[wait].js
  cypress/integration/default_spec.js
  lib/templates/createRequestObject.js
  lib/templates/netlifyFunction.js
  lib/templates/renderNextPage.js
Labels: type: feature
