Repository netlify/next-on-netlify, pull requests merged in 2020-11, with the labels that each got.

#72 github tools: fix fossa workflow file
  .github/workflows/fossa.yml
Labels: type: chore

#77 Update isRootCatchAllRedirect condition
  lib/helpers/isRootCatchAllRedirect.js
Labels: type: bug

#83 Add CI tests
  .github/workflows/workflow.yml
Labels: type: chore

#84 Add support for Node `10.17.0`.
  .github/workflows/workflow.yml
  package.json
  tests/helpers/buildNextApp.js
Labels: type: feature

#89 use configurable functionsDir and publishDir throughout NoN
  index.js
  lib/helpers/getNextConfig.js
  lib/helpers/getNextDistDir.js
  lib/helpers/setupNetlifyFunctionForPage.js
  lib/helpers/setupStaticFileForPage.js
  lib/pages/api/setup.js
  lib/pages/getInitialProps/setup.js
  lib/pages/getServerSideProps/setup.js
  lib/pages/getStaticProps/setup.js
  lib/pages/getStaticPropsWithFallback/setup.js
  lib/pages/getStaticPropsWithRevalidate/setup.js
  lib/pages/withoutProps/setup.js
  lib/steps/copyNextAssets.js
  lib/steps/copyPublicFiles.js
  lib/steps/prepareFolders.js
  lib/steps/setupPages.js
  lib/steps/setupRedirects.js
Labels: type: feature

#90 Upgrade version range of `next`
  package.json
Labels: type: feature

#91 Fix Node.js version in CI
  .github/workflows/workflow.yml
Labels: type: chore

#78 Add gemini.com to showcase
  README.md
Labels: type: feature

#92 Remove dependency: next-aws-lambda
  lib/config.js
  lib/helpers/setupNetlifyFunctionForPage.js
  lib/templates/createRequestObject.js
  lib/templates/createResponseObject.js
  lib/templates/netlifyFunction.js
  lib/templates/renderNextPage.js
  package-lock.json
  package.json
Labels: type: bug

#93 Fix: Add support for res.redirect in API routes
  cypress/fixtures/pages/api/redirect.js
  cypress/integration/default_spec.js
  lib/templates/createResponseObject.js
Labels: type: bug

#94 fix: dont empty publish/function paths unless theyre default
  lib/steps/prepareFolders.js
Labels: type: bug

#100 Improve logs when Functions/publish directories are specified
  lib/steps/prepareFolders.js
Labels: type: feature

#101 Fix Windows support
  .github/workflows/workflow.yml
  cypress/fixtures/package.json
  cypress/plugins/buildProject.js
  cypress/plugins/deployProject.js
  lib/helpers/getDataRouteForRoute.js
  package-lock.json
  package.json
  tests/customRedirects.test.js
  tests/defaults.test.js
  tests/fixtures/package.json
  tests/helpers/buildNextApp.js
  tests/helpers/npmRun.js
Labels: type: feature
