Repository netlify/next-on-netlify, pull requests merged in 2020-10, with the labels that each got.

#44 Copy host property from headers to multiValueHeaders
  lib/templates/netlifyFunction.js
Labels: bug

#62 Update README with logo and description
  README.md
  nextonnetlify.png
Labels: documentation, type: chore

#50 Support for SSG preview mode
  .gitignore
  README.md
  cypress/fixtures/pages-with-optionalCatchAll-at-root/[[...slug]].js
  cypress/fixtures/pages-with-optionalCatchAll-at-root/static.js
  cypress/fixtures/pages-with-optionalCatchAll-at-root/subfolder/[id].js
  cypress/fixtures/pages/api/enterPreviewStatic.js
  cypress/fixtures/pages/index.js
  cypress/fixtures/pages/previewTest/static.js
  cypress/fixtures/public/file.txt
  cypress/fixtures/public/folder/file.txt
  cypress/fixtures/public/subfolder/file.txt
  cypress/integration/default_spec.js
  cypress/integration/optionalCatchAll_at_root_spec.js
  lib/helpers/isRouteWithFallback.js
  lib/helpers/setupNetlifyFunctionForPage.js
  lib/pages/getStaticProps/pages.js
  lib/pages/getStaticProps/redirects.js
  lib/pages/getStaticProps/setup.js
  lib/pages/getStaticPropsWithRevalidate/pages.js
  lib/steps/setupRedirects.js
  tests/__snapshots__/defaults.test.js.snap
  tests/__snapshots__/optionalCatchAll.test.js.snap
  tests/customRedirects.test.js
  tests/getServerSidePropsIndexPage.test.js
  tests/staticIndexPages.test.js
Labels: type: feature
