Repository netlify/next-on-netlify, pull requests merged in 2021-03, with the labels that each got.

#173 Update Showcase
  README.md
  assets/showcase-bigbinary.png
Labels: type: chore

#174 copy dynamic import chunks to functions dirs
  lib/helpers/copyDynamicImportChunks.js
  lib/helpers/setupNetlifyFunctionForPage.js
  tests/configurableDirs.test.js
  tests/dynamicImports.test.js
  tests/fixtures/components/Header.js
  tests/fixtures/next.config.js-est
  tests/fixtures/pages-dynamic-imports/deep/import.js
  tests/fixtures/pages-dynamic-imports/index.js
Labels: type: bug

#178 More priority for deprecation
  README.md
Labels: documentation, type: chore
