Repository netlify/next-on-netlify, pull requests merged in 2021-02, with the labels that each got.

#163 fix: next 10.0.6 changed prerender-manifest for i18n
  lib/helpers/getPrerenderManifest.js
  package-lock.json
  package.json
  tests/fixtures/pages-i18n-ssg-index/index.js
  tests/i18n-ssg-root-index.test.js
Labels: type: bug

#162 feat: add watch mode
  README.md
  index.js
  lib/config.js
  lib/helpers/getNextDistDir.js
  lib/helpers/getNextSrcDir.js
  next-on-netlify.js
  package-lock.json
  package.json
Labels: type: feature

#167 remove next as peer dependency
  package-lock.json
  package.json
Labels: type: chore

#171 add support for background functions in api pages only
  README.md
  lib/helpers/getNetlifyFunctionName.js
  lib/helpers/setupNetlifyFunctionForPage.js
  lib/pages/api/redirects.js
  lib/pages/api/setup.js
  tests/__snapshots__/defaults.test.js.snap
  tests/__snapshots__/i18n.test.js.snap
  tests/defaults.test.js
  tests/fixtures/pages/api/hello-background.js
Labels: type: feature
