Repository netlify/next-on-netlify, pull requests merged in 2021-01, with the labels that each got.

#130 hotfix: redirect.added was unreliable espec in tests
  lib/steps/setupRedirects.js
Labels: type: bug

#131 hotfix index gsp pages in i18n
  lib/helpers/getPrerenderManifest.js
Labels: type: bug

#139 fix: fallback blocking would cause builds to crash
  lib/helpers/isRouteWithFallback.js
  tests/__snapshots__/defaults.test.js.snap
  tests/__snapshots__/i18n.test.js.snap
  tests/fixtures/pages/getStaticProps/withFallbackBlocking/[id].js
Labels: type: bug

#138 initial support for next/image on netlify
  README.md
  index.js
  lib/config.js
  lib/steps/setupImageFunction.js
  lib/steps/setupRedirects.js
  lib/templates/imageFunction.js
  package-lock.json
  package.json
  tests/__snapshots__/defaults.test.js.snap
  tests/__snapshots__/i18n.test.js.snap
  tests/__snapshots__/optionalCatchAll.test.js.snap
  tests/defaults.test.js
  tests/preRenderedIndexPages.test.js
  tests/staticIndexPages.test.js
Labels: type: feature

#141 generate _headers file to override static chunks cache control
  index.js
  lib/config.js
  lib/steps/setupHeaders.js
  tests/__snapshots__/defaults.test.js.snap
  tests/defaults.test.js
Labels: type: feature

#134 track NoN files when configured dirs are used, clean before each new run
  index.js
  lib/helpers/handleFileTracking.js
  lib/steps/prepareFolders.js
  tests/configurableDirs.test.js
  tests/fixtures/my-functions/someTestFunction.js
  tests/helpers/buildNextApp.js
Labels: type: bug

#142 fix windows test in file tracking work
  README.md
  lib/helpers/handleFileTracking.js
  tests/fixtures/.nonfiletracking
  tests/fixtures/my-functions/next_image.js
Labels: type: bug

#144 fix incorrect _headers syntax & broken local cypress
  cypress/plugins/deployProject.js
  lib/steps/setupHeaders.js
  tests/__snapshots__/defaults.test.js.snap
  tests/customHeaders.test.js
  tests/fixtures/_headers
Labels: type: bug

#145 revert route/redirect sorting logic to static then dynamic
  lib/helpers/getSortedRedirects.js
  lib/helpers/getSortedRoutes.js
  lib/steps/setupRedirects.js
  tests/__snapshots__/defaults.test.js.snap
  tests/__snapshots__/i18n.test.js.snap
  tests/__snapshots__/optionalCatchAll.test.js.snap
  tests/staticIndexPages.test.js
Labels: type: bug

#149 revert next/image support until jimp module issue is resolved
  index.js
  tests/defaults.test.js
Labels: type: bug

#150 check existence of dirs before reading them in file tracking logic
  lib/helpers/handleFileTracking.js
Labels: type: bug

#152 remove unneccessary * from headers rule that broke ntl dev
  cypress/plugins/deployProject.js
  lib/steps/setupHeaders.js
  tests/__snapshots__/defaults.test.js.snap
Labels: type: bug

#148 throw error if .next/static cannot be found
  lib/steps/copyNextAssets.js
Labels: type: bug

#146 prevent copy of .public to .public
  index.js
  lib/steps/copyPublicFiles.js
Labels: type: bug

#156 strip file extension when checking if route is dynamic in setupRedirects
  cypress/fixtures/pages-with-optionalCatchAll-at-root/[bar]/ssr.js
  cypress/fixtures/pages-with-optionalCatchAll-at-root/home.js
  cypress/integration/optionalCatchAll_at_root_spec.js
  lib/helpers/getSortedRedirects.js
  lib/helpers/removeFileExtension.js
  lib/steps/copyNextAssets.js
  lib/steps/setupRedirects.js
  tests/__snapshots__/defaults.test.js.snap
  tests/__snapshots__/i18n.test.js.snap
  tests/__snapshots__/optionalCatchAll.test.js.snap
Labels: type: bug

#155 feat: enhance README
  README.md
Labels: type: feature

#158 next/image support back after internal functions dep work
  index.js
  tests/defaults.test.js
Labels: type: bug, type: feature

#159 fix image url in imageFunction
  lib/templates/imageFunction.js
Labels: type: bug

#161 chore: support Node 15
  .github/workflows/workflow.yml
Labels: type: chore

#160 Update README with clearer setup/deploy instructions
  README.md
Labels: type: chore
